import db from '@adonisjs/lucid/services/db'
import Journal from '#models/journal'
const invalid = (message: string) => { const e = new Error(message) as Error & { code: string; messages: unknown[] }; e.code = 'E_VALIDATION_ERROR'; e.messages = [{ message, rule: 'journal', field: 'lines' }]; return e }
const validateLines = async (lines: any[]) => { if (!lines || lines.length < 2) throw invalid('At least two journal lines are required'); const heads = await db.from('account_heads').whereIn('id', lines.map((line) => line.accountHeadId)); if (heads.length !== new Set(lines.map((line) => line.accountHeadId)).size) throw invalid('Every account head must exist'); const subHeads = await db.from('account_sub_heads').whereIn('id', lines.map((line) => line.accountSubHeadId)); if (subHeads.length !== new Set(lines.map((line) => line.accountSubHeadId)).size) throw invalid('Every account sub-head must exist'); if (lines.some((line) => line.debit < 0 || line.credit < 0 || (line.debit > 0 && line.credit > 0) || (line.debit === 0 && line.credit === 0))) throw invalid('Each line must have one non-negative debit or credit value'); const debit = lines.reduce((sum, line) => sum + Math.round(Number(line.debit) * 100), 0); const credit = lines.reduce((sum, line) => sum + Math.round(Number(line.credit) * 100), 0); if (debit !== credit) throw invalid('Total Debit must equal Total Credit'); }
export const createJournal = async (payload: any) => { await validateLines(payload.lines); const trx = await db.transaction(); try { const [journal] = await trx.table('journals').insert({ journal_number: payload.journalNumber, journal_date: payload.journalDate, journal_type: payload.journalType, transaction_type: payload.transactionType, party_heads: payload.partyHeads, description: payload.description, status: payload.status ?? 'posted' }).returning('id'); await trx.table('journal_lines').insert(payload.lines.map((line: any) => ({ journal_id: journal.id, account_head_id: line.accountHeadId, account_sub_head_id: line.accountSubHeadId, narration: line.narration, debit: line.debit, credit: line.credit }))); await trx.commit(); return getJournal(journal.id) } catch (e) { await trx.rollback(); throw e } }
export const listJournals = () => Journal.query().preload('lines').orderBy('id', 'desc')
export const getJournal = async (id: number) => { const item = await Journal.query().where('id', id).preload('lines').first(); if (!item) throw new Error(`Journal with ID: ${id} does not exist`); return item }
export const updateJournal = async (id: number, payload: any) => { await getJournal(id); if (payload.lines) await validateLines(payload.lines); const trx = await db.transaction(); try { const journalChanges = Object.fromEntries(Object.entries({ journal_date: payload.journalDate, journal_type: payload.journalType, transaction_type: payload.transactionType, party_heads: payload.partyHeads, description: payload.description, status: payload.status }).filter(([, value]) => value !== undefined)); if (Object.keys(journalChanges).length) await trx.from('journals').where('id', id).update(journalChanges); if (payload.lines) { await trx.from('journal_lines').where('journal_id', id).delete(); await trx.table('journal_lines').insert(payload.lines.map((line: any) => ({ journal_id: id, account_head_id: line.accountHeadId, account_sub_head_id: line.accountSubHeadId, narration: line.narration, debit: line.debit, credit: line.credit }))) } await trx.commit(); return getJournal(id) } catch (e) { await trx.rollback(); throw e } }
export const deleteJournal = async (id: number) => { await getJournal(id); await db.from('journals').where('id', id).delete() }
