version: '0.2'
language: en-GB
dictionaries:
  - typescript
  - node
  - softwareTerms
  - npm
  - filetypes
ignorePaths:
  - node_modules
  - build
  - dist
  - coverage
  - .git
  - public/jsonfiles
  - package.json

words:
  - tinyint
  - mediumtext
  - disp
  - extnames
  - Findh
  - benhepburn
  - tokenable
  - Ignitor
  - vinejs
  - EYTS
  - SENCO
  - OOSC
  - networkidle
  - mjml
  - uuidv
  - bullmq
  - jsonfiles
  - bodyparser
  - japa
  - teardown
  - AdonisJS
  - devtool
  - envfile
  - onboardly
  - heyed
  - Asmera
  - Ceuta
  - Douala
  - Aaiun
  - Adak
  - Ensenada
  - Araguaina
  - Catamarca
  - Comod
  - Rivadavia
  - Comod
  - Rivadavia
  - Jujuy
  - Rioja
  - Gallegos
  - Salta
  - Tucuman
  - Ushuaia
  - Atikokan
  - Atka
  - Bahia
  - Banderas
  - Sablon
  - Catamarca
  - Cuiaba
  - Danmarkshavn
  - Eirunepe
  - Godthab
  - Hermosillo
  - Vevay
  - Winamac
  - Inuvik
  - Jujuy
  - Kralendijk
  - Maceio
  - Manaus
  - Matamoros
  - Mazatlan
  - Merida
  - Metlakatla
  - Nipigon
  - Ojinaga
  - Pangnirtung
  - Velho
  - timezones
  - create_prorations
  - lodash-omitdeep
  - hsts
  - toMillis
  - theexpertscloud
  - DATEDIFF
